# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 962a8ccc0c2c619c59666f128ad9cc14f7998a59baef42c9e80802c23766865898d883ea43e8fc19a1caef652ee8bcbdbe6f9066d93d502ee0f8c01e7bfda4bd

test:
  secret_key_base: c1441647fe0a40fe71f512754b4b47b7863745ae055d7b3b010482374225a8a2028aaf8359f9d9f65ef71ba76e91a56bf9325a73b251a1a31354c9e6af9b6863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
